staging: android: lowmemorykiller: Add config option to support oom_adj values
The conversion to use oom_score_adj instead of the deprecated oom_adj
values breaks existing user-space code. Add a config option to convert
oom_adj values written to oom_score_adj values if they appear to be
valid oom_adj values.

Change-Id: I68308125059b802ee2991feefb07e9703bc48549
Signed-off-by: Arve Hjønnevåg <arve@android.com>

Upgrade LMK to 3.4 source.
Errors killed:
-negative width in bit-field
-undefined reference to `drop_pagecache_sb'
Signed-off-by: Demetris Ierokipides <ierokipides.dem@gmail.com>

Conflicts:
	drivers/staging/android/lowmemorykiller.c